### ISSUE TITLE
A way to not have `run()` with a closure? 

### ISSUE THREAD

**Issue by elpiel** [khuey/bb8#19] opened 2019-05-09 15:36 UTC
First of all - sorry for my ignorance, I'm new to Rust.
In the project I am working we want to use bb8 and we're successfully using it, but something like that:
```
let fut = self.db_pool
            .run(move |mut conn| {
                conn.prepare("SELECT channel_id, creator, deposit_asset, deposit_amount, valid_until FROM channels")
                    .then(move |res| match res {
                        Ok(stmt) => {
                            conn
                                .query(&stmt, &[])
                                .collect()
                                .into_future()
                                .then(|res| match res {
                                    Ok(rows) => Ok((rows, conn)),
                                    Err(err) => Err((err, conn)),
                                })
                                .into()
                        }
                        Err(err) => try_future!(Err((err, conn))),
                    })
                    .and_then(|(rows, conn)| {
                        let channels = rows.iter().map(|row| {
                            Channel {
                                id: row.get("channel_id"),
                                creator: row.get("creator"),
                                deposit_asset: row.get("deposit_asset"),
                                deposit_amount: row.get("deposit_amount"),
                                valid_until: row.get("valid_until"),
                            }
                        }).collect();

                        Ok((channels, conn))
                    })
            })
            .map_err(|err| handle_internal_error(&err));
```

Looks quite, well - unbreakable. + we cannot use `await!()` inside the closure.

From my understanding some things are happening in `run()` that handle the dropping/idling of the connection. Isn't it possible that this can be change in such a way that `Drop` (or tbh I don't know what exactly) is implemented that `run()` can return the connection and we can use it with `await!()`, but also as a future and to get rid of the tidies `Ok((channels, conn))` returns?

Thank you in advance! I will be happy to help and implement this as long as I understand how.

**Comment by jannschu** [comment] 2019-07-30 10:56
I think r2d2 does implement something similar. There, a `PooledConnection` struct is used which has a reference to the pool. The pooled connection puts itself back into the pool upon `Drop`.

I would also be interested in that.

**Comment by bikeshedder** [comment] 2019-07-31 12:32
I'm quite new to Rust async development but had some struggles with the `run` function, too. Is it possible to provide a `Pool::get() -> Future<Client, Error>`? I think that's how [L3-37](https://github.com/OneSignal/L3-37) does it.

The `Future<(_, Client)>` return value feels wrong to me.

**Comment by elpiel** [comment] 2019-11-14 06:28
@khuey with the help of @djc we've managed to get the drop-based interfaces.
Would it be possible for you to check it out and give your thoughts, please?
https://github.com/djc/bb8/pull/3

**Comment by bikeshedder** [comment] 2019-11-21 21:39
Using a drop based interface which blocks in an async function is wrong and could cause very awkward deadlocks when the entire reactor hangs because of that.

I recently released `deadpool-postgres` which is based on async-await and has a non-blocking drop based interface. It doesn't support any of the advanced r2d2/bb8 features and doesn't even aim to compete in scenarios where a more sophisticated connection pooling is desired. It's just `dead simple`: https://crates.io/crates/deadpool-postgres/

**Comment by djc** [comment] 2019-12-31 08:38
This is in the process of being fixed in #45.

**Closed** 2020-01-01 16:36 UTC

**Comment by djc** [comment] 2020-01-02 19:46
@bikeshedder, why is `drop()` blocking in an async function worse than other kinds of blocking? I don't necessarily see why blocking in `drop()` is worse than outside `drop()` for this.

**Comment by bikeshedder** [comment] 2020-01-02 20:44
If you block in an `async` fn you can end up blocking the executor that is responsible for unlocking the locking primitive you're waiting for. Thus resulting in a deadlock.

In the case of bb8 this can happen quite easily:

1. Use a tokio executor with only one thread. e.g. `#[tokio:main(basic_scheduler)]`
2. Grab a connection `A` from the pool
3. Grab a connection `B` from the pool - that call gets interrupted while holding the mutex lock
4. Drop connection `B` which now calls `futures::executor::block_on` which blocks the executor and waits for the lock which never gets released.

This can also happen with a multi threaded executor as well and will result in hard to reproduce deadlocks. It should be fine to replace that `block_on` call by something like `tokio::spawn` and get rid of this problem.

Also there is another thing to be aware of: Futures are not guaranteed to run to completion. Every time you put an `.await` in your code ask yourself what happens if that code is never run to completion. e.g. https://github.com/khuey/bb8/blob/master/bb8/src/lib.rs#L458 - `pending_connections` is increased by one (L449) and never reduced again. If the future is interrupted at L458 the count will be off by one. The only way to fix this is by adding a guard implementing a `Drop` trait to fix the internal state. And this needs to be done without blocking or you can run into the deadlock issue again.

That is by the way exactly how I solved this problem in `deadpool`: https://github.com/bikeshedder/deadpool/blob/master/src/lib.rs#L107 - In the case of `deadpool` it's much simpler as the entire code base only contains 3 `await`s and uses the new `Semaphore` locking primitive from `tokio` and the non blocking `Queue` from `crossbeam`.

When benchmarking various pools (bb8, l337, r2d2) in the past I did run into actual deadlocks with `bb8`. One way to test this is by writing a simple `hyper` server and benchmarking it with `wrk`. Upon test completion `wrk` closes the `TCP` sockets and doesn't wait for completion. Hyper in response stops executing the futures as the results are no longer needed.

Hope that helps.

**Comment by djc** [comment] 2020-01-16 21:27
@bikeshedder, thanks a bunch, this is a great explanation! I'll probably look at your code for some inspiration. I've made some changes so that it shouldn't be a problem not to run to completion.
