### ISSUE TITLE
stucked server 

### ISSUE THREAD

**Issue by invis87** [khuey/bb8#84] opened 2020-10-22 13:47 UTC
In current project my team needs a middleware service between redis and rest of the world. So I wrote one that use bb8-redis under the hood, but unfortunately it stucks under a lot of connections.

I create repo with instructions how to reproduce, [here it is](https://github.com/invis87/bb8_redis_stuck).

**Comment by invis87** [comment] 2020-10-23 16:36
with `mobc` pool all works fine!

**Comment by djc** [comment] 2020-11-05 10:15
I don't have an easy test environment, but I just spent quite a bit of time to improve the implementation. Please test current master and let me know if it works better for you.

**Comment by djc** [comment] 2020-11-05 10:20
Going to close this as a duplicate of #67 for now.

**Closed by djc** 2020-11-05 10:20 UTC

**Comment by invis87** [comment] 2020-11-05 15:29
No longer reproducible.
Good job!

**Comment by djc** [comment] 2020-11-05 15:34
Thanks for testing!
