### ISSUE TITLE
Postgres example `async_await` in latest version not work. TimedOut

### ISSUE THREAD

**Issue by friktor** [khuey/bb8#54] opened 2020-01-16 08:18 UTC
I try to use last 0.4 version from that repo, but library panic after try use connection. Pool is succesfuly created, but after send query - failed with TimedOut. Also i tried use that in my project with actix, and same - the pool is created successfully, but then it breaks when trying to send a request.
@djc Is this a known bug? Maybe it does not work because it is only an alpha version.
(I attach you because it looks like the project passed to you)

**Comment by djc** [comment] 2020-01-16 08:24
Did you make sure the username and password in the example code are correct for your database?

**Comment by friktor** [comment] 2020-01-16 08:42
@djc yep of course, url also used for synchronous r2d2 connection

**Comment by djc** [comment] 2020-01-16 14:20
The `async_await` example is working for me on current master, as long as I get the credentials correct, including a database that the user can actually access.

**Comment by djc** [comment] 2020-01-16 14:21
On the other hand, the `hyper` example seems to time out for me, so there's probably still an issue somewhere.

**Comment by djc** [comment] 2020-01-17 20:57
I was looking at the `hyper` example incorrectly -- it seems to be working fine for me.

**Comment by djc** [comment] 2020-05-21 12:44
Since there has been no further feedback here, going to close this. Feel free to reopen if you still see reproducible issues.

**Closed by djc** 2020-05-21 12:44 UTC
